# Site settings
title: Jay Flaunts His Ignorance. The podcast.
email: jay+flaunts@jays.net
description: > # this means to ignore newlines until "baseurl:"
  Jay Hannah running around talking to interesting people about whatever
  they're excited about. 
baseurl: "/jayflaunts" # the subpath of your site, e.g. /blog/
url: "http://jhannah.github.io" # the base hostname & protocol for your site
twitter_username: jayflaunts
github_username:  jhannah

# Build settings
markdown: kramdown
